// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABzL04Qnke6iKF2T0SwFJWxelFC3zoVUo',
    appId: '1:620681770588:web:906cfdb8eaee83db9b1899',
    messagingSenderId: '620681770588',
    projectId: 'chat-app-5d03b',
    authDomain: 'chat-app-5d03b.firebaseapp.com',
    storageBucket: 'chat-app-5d03b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb0PRaQy1zhlyVc2RIPVylM6qL6LTulbs',
    appId: '1:620681770588:android:8cdc008cba164f089b1899',
    messagingSenderId: '620681770588',
    projectId: 'chat-app-5d03b',
    storageBucket: 'chat-app-5d03b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZnIkcIFE6IWcCoVLhauaAVJgQh63_z0',
    appId: '1:620681770588:ios:387250a6d62448d29b1899',
    messagingSenderId: '620681770588',
    projectId: 'chat-app-5d03b',
    storageBucket: 'chat-app-5d03b.appspot.com',
    iosClientId: '620681770588-kp266gta0pqv372d7rmlpvogr9frerb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZnIkcIFE6IWcCoVLhauaAVJgQh63_z0',
    appId: '1:620681770588:ios:128a94f1dfaa584c9b1899',
    messagingSenderId: '620681770588',
    projectId: 'chat-app-5d03b',
    storageBucket: 'chat-app-5d03b.appspot.com',
    iosClientId: '620681770588-03f7mldjto11ddralev35tbfsdkk9e9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABzL04Qnke6iKF2T0SwFJWxelFC3zoVUo',
    appId: '1:620681770588:web:378bffe95cba852e9b1899',
    messagingSenderId: '620681770588',
    projectId: 'chat-app-5d03b',
    authDomain: 'chat-app-5d03b.firebaseapp.com',
    storageBucket: 'chat-app-5d03b.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyABzL04Qnke6iKF2T0SwFJWxelFC3zoVUo',
    appId: '1:620681770588:web:256f109efbce95d49b1899',
    messagingSenderId: '620681770588',
    projectId: 'chat-app-5d03b',
    authDomain: 'chat-app-5d03b.firebaseapp.com',
    storageBucket: 'chat-app-5d03b.appspot.com',
  );
}
